### ISSUE TITLE
Binary build error

### ISSUE THREAD

**Issue by hdashnow** [quinlan-lab/STRling#101]
@brentp I'm having some trouble compiling the binaries. Following these instructions:
https://strling.readthedocs.io/en/latest/contribute.html

```
stack trace: (most recent call last)
argparse.nim(881, 23)    tmpmkParser
argparse.nim(724, 31)    mkParser
argparse.nim(587, 36)    genParseProcs
macrohelp.nim(60, 8)     parentOf
/scratch/ucgd/lustre-work/quinlan/u6026198/git/STRling/src/strpkg/genome_strs.nim(172, 20) template/generic instantiation of `newParser` from here
/uufs/chpc.utah.edu/common/HIPAA/u6026198/.nimble/pkgs/argparse-0.7.1/argparse/macrohelp.nim(60, 8) Error: node not found: EXTRA
error compiling code
```

**Comment by brentp** [comment]
Hi, I get a successful compile for 06c0820 with:
```
singularity run --bind $(pwd):/load --bind /home  'docker://brentp/musl-hts-nim:v0.3.17' /usr/local/bin/nsb -n strling.nimble -s src/strling.nim -- -d:danger -d:release -d:debug
```
which is what's shown in that page. But, as a side node. adding `-d:debug` removes the effects of `-d:danger` and `-d:release`.
Can you show the full command that you are running?

**Comment by brentp** [comment]
On 2nd look, maybe your $HOME nim stuff on the host is still getting into the container. You can try adding, e.g.:

```
singularity run --home /tmp/fake-home/ ...
```

to see if that helps. Also see --no-home option to singularity run.

**Comment by hdashnow** [comment]
Thanks @brentp, got it working!
