### ISSUE TITLE
Multiallelic STRs

### ISSUE THREAD

**Issue by themkdemiiir** [quinlan-lab/STRling#120]
Hey, thanks for the great tool. How are you dealing with problems related to multiallelic short tandem repeats? For example, RFC1.

https://github.com/broadinstitute/str-analysis/issues/12#issue-2136249713

**Comment by hdashnow** [comment]
We make a separate call for each motif. The cis/trans arrangement is uncertain, however.

Here is an example from 1000 genomes, sample HG00103:
```
#chrom	left	right	repeatunit	allele1_est	allele2_est	anchored_reads	spanning_reads	spanning_pairs	expected_spanning_pairs	spanning_pairs_pctl	left_clips	right_clips	unplaced_pairs	depth	sum_str_counts
chr4 39348432        39348476        AAGGG   0.00    7.16    0       6       5       39.64   0.01    4       0       0       32.0    35
chr4 39348424        39348483        AAAAG   0.00    36.61   19      0       0       37.33   0.00    1       0       0       32.0    547
```
