### ISSUE TITLE
Unexpectedly high number of anchored reads reported

### ISSUE THREAD

**Issue by hdashnow** [quinlan-lab/STRling#14]
6 anchored reads reported, but I think there should only be 3. There are 3 soft-clipped reads in this picture that have MAPQ>20.

chr22.hg38-genotype.txt:
```chr12	78702630	78702631	CCAAA	nan	inf	6	0	0	3	0	0	0.0	32```

chr22.hg38-reads.txt:
```
chr12	78702630	CCAAA	left	4	52878202_52878488_1553162_1	205
chr12	78702630	CCAAA	left	3	52878289_52878490_1671274_0	205
chr12	78702630	CCAAA	left	1	52878247_52878503_2966158_0	205
chr12	78702654	CCAAA	none	8	52878202_52878488_1553162_1	205
chr12	78702654	CCAAA	none	8	52878247_52878503_2966158_0	205
chr12	78702654	CCAAA	none	8	52878289_52878490_1671274_0	205
```

Data here:
`/uufs/chpc.utah.edu/common/HIPAA/u6026198/storage/git/STRling/working/ref_sim`
Simulated reference reads from chr22, aligned to hg38

![chr12](https://user-images.githubusercontent.com/3794821/67530748-5641ab80-f67d-11e9-9ae8-3e0545063c85.png)

**Comment by brentp** [comment]
https://github.com/quinlan-lab/STRling/blob/master/src/strpkg/genotyper.nim#L147-L147

**Comment by hdashnow** [comment]
I can't actually find a place where the number of anchored reads is calculated. I don't think `total - clipped` would be correct. A read could be both.

**Comment by hdashnow** [comment]
So the output is reporting total reads, not anchored reads. So this isn't an error. May want to report the number of anchored reads in the future, but not vital for the moment. Closing.
