### ISSUE TITLE
align_length > 0 Assertion Error

### ISSUE THREAD

**Issue by christopher-schroeder** [quinlan-lab/STRling#43]
Hello,
with the current version 0.1.0 I get the following assertion Error. The file was align with bwa mem, duplicates removes with samblaster and sorting accomplished by sambamba. Did I do something wrong?

[strling] finding STR regions on reference chromosome: 1
[strling] finding STR regions on reference chromosome: 2
[strling] finding STR regions on reference chromosome: 3
[strling] finding STR regions on reference chromosome: 4
[strling] finding STR regions on reference chromosome: 5
[strling] finding STR regions on reference chromosome: 6
[strling] finding STR regions on reference chromosome: 7
[strling] finding STR regions on reference chromosome: 8
[strling] finding STR regions on reference chromosome: 9
[strling] finding STR regions on reference chromosome: 10
[strling] finding STR regions on reference chromosome: 11
[strling] finding STR regions on reference chromosome: 12
[strling] finding STR regions on reference chromosome: 13
[strling] finding STR regions on reference chromosome: 14
[strling] finding STR regions on reference chromosome: 15
[strling] finding STR regions on reference chromosome: 16
[strling] finding STR regions on reference chromosome: 17
[strling] finding STR regions on reference chromosome: 18
[strling] finding STR regions on reference chromosome: 19
[strling] finding STR regions on reference chromosome: 20
[strling] finding STR regions on reference chromosome: 21
[strling] finding STR regions on reference chromosome: 22
[strling] finding STR regions on reference chromosome: X
[strling] finding STR regions on reference chromosome: Y
[strling] found 3327 STR-like regions in the genome
[strling] got STR repeats from genome into an interval tree
[strling] collecting str-like reads
[strling] extracting chromosome:1
fatal.nim(39)            sysFatal
Error: unhandled exception: extract.nim(80, 12) `align_length > 0` A00786:99:HW2C2DSXX:4:2161:9245:35665        117     1       153708993       0       *       =      153708993        0       *   *   MC:Z:93S35M23S  AS:i:0  XS:i:0  RG:Z:EPF-DAN-024-048 [AssertionError]

**Comment by brentp** [comment]
I see the problem. We will fix for next release. Thanks for reporting.

**Comment by hdashnow** [comment]
@brentp can I confirm this is fixed in 0.2.0?

**Comment by hdashnow** [comment]
I think this has been fixed, but please reopen if you see this issue in the latest version.
