### ISSUE TITLE
Off by 1 errors when detecting if a read spans a locus?

### ISSUE THREAD

**Issue by hdashnow** [quinlan-lab/STRling#6]
See CANVAS genomes. Unexpected spanning reads/pairs.

**Comment by hdashnow** [comment]
These samples are probably all homozygous for a large novel expansion at this locus:
(hg19)

start | stop | disease | gene | repeatunit
-- | -- | -- | -- | --
39350045 | 39350103 | CANVAS | RFC1 | AAGGG

We would not expect to get any spanning reads or spanning pairs. Possible bug? Some of these reads/pairs do not actually span?

These three samples have reported spanning reads/pairs:
- D16_0518
- D17_0397
- D17_0398

(there are also two other samples in that directory with the same variant, but no spanning reads/pairs reported)

Binary intermediate files and other outputs:
`/uufs/chpc.utah.edu/common/HIPAA/u6026198/storage/git/str-dev/working/novel-true-pos`

Commands:
```
/uufs/chpc.utah.edu/common/HIPAA/u6026198/storage/git/str-dev/src/str call -f /uufs/chpc.utah.edu/common/HIPAA/u6026198/storage/ref-data/hg19/hg19.fa -v -o D16_0518 /uufs/chpc.utah.edu/common/HIPAA/u6026198/storage/data/STR_true_pos/from_Sarah_2019/D16_0518.bam.BamOrder.ApplyBQSR.bam D16_0518.str.bin
/uufs/chpc.utah.edu/common/HIPAA/u6026198/storage/git/str-dev/src/str call -f /uufs/chpc.utah.edu/common/HIPAA/u6026198/storage/ref-data/hg19/hg19.fa -v -o D17_0398 /uufs/chpc.utah.edu/common/HIPAA/u6026198/storage/data/STR_true_pos/from_Sarah_2019/D17_0398.bam.BamOrder.ApplyBQSR.bam D17_0398.str.bin
/uufs/chpc.utah.edu/common/HIPAA/u6026198/storage/git/str-dev/src/str call -f /uufs/chpc.utah.edu/common/HIPAA/u6026198/storage/ref-data/hg19/hg19.fa -v -o D17_0397 /uufs/chpc.utah.edu/common/HIPAA/u6026198/storage/data/STR_true_pos/from_Sarah_2019/D17_0397.bam.BamOrder.ApplyBQSR.bam D17_0397.str.bin
```

**Comment by brentp** [comment]
so we are counting any read that spans this interval as "supporting". here is the code that does it:
https://github.com/quinlan-lab/STRling/blob/4d60eb53df8a149493b39c974a436d3299e89908/src/strpkg/collect.nim#L86-L97

instead of `result = true` we should have `result = (support.SpanningRepeatCount > ??)` 

I guess what to do depends on what we need from this function. 

Note that this:

```
    support.SpanningReadRepeatCount = A.count(bounds).uint8
```
is just doing a simple string count of the number of times the repeat is seen within those bounds so it will include counts of the reference allele. also, this is not requiring a certain percentage of the bounds to be covered by the repeat unit (as we do elsewhere). 

any thoughts on how to proceed?

**Comment by hdashnow** [comment]
The problem:
This locus is a 1bp bound. And we are incorrectly placing it 1bp, to the left (possibly 2bp). So we are incorrectly attributing reads/pairs as spanning. 
Solution: require 2-3 bp for slop for to define a read/pair as spanning.

**Comment by hdashnow** [comment]
Puzzling over why I'm still getting 8 spanning reads in this sample (bounds region indicated by the 1bp blue block in the bottom track)

![spanning_reads](https://user-images.githubusercontent.com/3794821/66965320-7d252f80-f036-11e9-8e93-3fd59ccb4e97.png)

**Comment by brentp** [comment]
PR is up-to-date?

**Comment by hdashnow** [comment]
It is now. I just fixed the test.

**Comment by brentp** [comment]
what is the size of the repeat unit?

**Comment by hdashnow** [comment]
5bp 
AAGGG

**Comment by hdashnow** [comment]
PS only sample D16_0518 is still having this issue. Other two are fixed

**Comment by brentp** [comment]
if you scroll down in igv, there are no weird reads covering this?

**Comment by hdashnow** [comment]
No. It's those reads. I checked the IDs. I am having issues with different versions of IGV showing me sightly different things though 😱

**Comment by hdashnow** [comment]
In spite of some weirdness with IGV, the algorithm is doing what I intended.
These are the offending reads. They do technically span the bounds, even with a few bp of slop. But it's pretty clear that they don't span the true allele (because the allele is larger than a read, and it's obvious on IGV that they don't span). So they definitely shouldn't be considered spanning. I think this is going to be a problem for all small bounds (which is likely to happen for novel insertions), so it does need a solution... It's particularly problematic at this locus because there is both a deletion and an insertion, so the bounds sit on the left side of a deleted region.

Bounds: 39350045 39350046
Slop: 4

A00121:66:HFH3HDSXX:4:1321:10818:8923 39349903 39350053
Spanning: 142 7 (bp in the read that span the bounds, left and right, respectively)
 
A00121:66:HFH3HDSXX:4:2155:17255:32628 39349907 39350052
Spanning: 138 6
 
A00121:66:HFH3HDSXX:4:2266:1606:33583 39349915 39350052
Spanning: 130 6
 
A00121:66:HFH3HDSXX:4:1439:31439:28792 39349917 39350053
Spanning: 128 7

A00121:66:HFH3HDSXX:4:1133:25238:31798 39349918 39350052
Spanning: 127 6
 
A00121:66:HFH3HDSXX:4:1571:3287:4867 39349927 39350052
Spanning: 118 6
 
A00121:66:HFH3HDSXX:4:2273:15718:25770 39349929 39350052
Spanning: 116 6
 
A00121:66:HFH3HDSXX:4:1123:7798:16157 39349937 39350052
Spanning: 108 6

**Comment by hdashnow** [comment]
I decided to require even more slop for bounds that are less than 5bp wide. This fixes this example. I'm not sure if it's a good general rule of thumb though... Might have to revisit this down the track after looking at more novel loci.
