### ISSUE TITLE
Parsing issue with outliers.py 

### ISSUE THREAD

**Issue by jgunti-code** [quinlan-lab/STRling#63]
I am having a problem with the controls file in the outliers.py 
Traceback (most recent call last):
  File "/projects/b1073/pipelines/genomes/jrg_sandbox/str_callers/outliers.py", line 448, in <module>
    main()
  File "/projects/b1073/pipelines/genomes/jrg_sandbox/str_callers/outliers.py", line 289, in main
    control_estimates = parse_controls(control_file)
  File "/projects/b1073/pipelines/genomes/jrg_sandbox/str_callers/outliers.py", line 99, in parse_controls
    control_estimates = pd.read_csv(control_file, index_col=0, delim_whitespace = True, header = None)
  File "/home/jrg4257/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/jrg4257/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 463, in _read
    data = parser.read(nrows)
  File "/home/jrg4257/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1154, in read
    ret = self._engine.read(nrows)
  File "/home/jrg4257/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2059, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 881, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 896, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 950, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 937, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2132, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 3 fields in line 131145, saw 4

**Comment by hdashnow** [comment]
Was the control file generated by the same script? Could you please provide a snippet of the file, perhaps the head, and the line that cause the error: line 131145 according to the error message above.
Also, could you please confirm which version of the script you are using? The commit hash would be fine, since it's not released yet.

**Comment by jgunti-code** [comment]
Hi, yes I used the code:
`python outliers.py \
--genotypes XYZ_986_02-genotype.txt XYZ_987_02-genotype.txt XYZ_988_02-genotype.txt XYZ_989_02-genotype.txt XYZ_TS0_02-genotype.txt XYZ_TS1_02-genotype.txt XYZ_TS2_02-genotype.txt XYZ_TS3_02-genotype.txt XYZ_TS4_02-genotype.txt XYZ_TS5_02-genotype.txt XYZ_TS6_02-genotype.txt XYZ_TS7_02-genotype.txt XYZ_TS8_02-genotype.txt XYZ_986_03-genotype.txt XYZ_987_03-genotype.txt XYZ_988_03-genotype.txt XYZ_989_03-genotype.txt XYZ_TS0_03-genotype.txt XYZ_TS1_03-genotype.txt XYZ_TS2_03-genotype.txt XYZ_TS3_03-genotype.txt XYZ_TS4_03-genotype.txt XYZ_TS5_03-genotype.txt XYZ_TS6_03-genotype.txt XYZ_TS7_03-genotype.txt XYZ_TS8_03-genotype.txt \
--unplaced XYZ_986_02-unplaced.txt XYZ_987_02-unplaced.txt XYZ_988_02-unplaced.txt XYZ_989_02-unplaced.txt XYZ_TS0_02-unplaced.txt XYZ_TS1_02-unplaced.txt XYZ_TS2_02-unplaced.txt XYZ_TS3_02-unplaced.txt XYZ_TS4_02-unplaced.txt XYZ_TS5_02-unplaced.txt XYZ_TS6_02-unplaced.txt XYZ_TS7_02-unplaced.txt XYZ_TS8_02-unplaced.txt XYZ_986_03-unplaced.txt XYZ_987_03-unplaced.txt XYZ_988_03-unplaced.txt XYZ_989_03-unplaced.txt XYZ_TS0_03-unplaced.txt XYZ_TS1_03-unplaced.txt XYZ_TS2_03-unplaced.txt XYZ_TS3_03-unplaced.txt XYZ_TS4_03-unplaced.txt XYZ_TS5_03-unplaced.txt XYZ_TS6_03-unplaced.txt XYZ_TS7_03-unplaced.txt XYZ_TS8_03-unplaced.txt \
--emit med_std_devs_controls

python outliers.py \
--genotypes XYZ_986_01-genotype.txt XYZ_987_01-genotype.txt XYZ_988_01-genotype.txt XYZ_989_01-genotype.txt XYZ_TS0_01-genotype.txt XYZ_TS1_01-genotype.txt XYZ_TS2_01-genotype.txt XYZ_TS3_01-genotype.txt XYZ_TS4_01-genotype.txt XYZ_TS5_01-genotype.txt XYZ_TS6_01-genotype.txt XYZ_TS7_01-genotype.txt XYZ_TS8_01-genotype.txt XYZ_986_02-genotype.txt XYZ_987_02-genotype.txt XYZ_988_02-genotype.txt XYZ_989_02-genotype.txt XYZ_TS0_02-genotype.txt XYZ_TS1_02-genotype.txt XYZ_TS2_02-genotype.txt XYZ_TS3_02-genotype.txt XYZ_TS4_02-genotype.txt XYZ_TS5_02-genotype.txt XYZ_TS6_02-genotype.txt XYZ_TS7_02-genotype.txt XYZ_TS8_02-genotype.txt XYZ_986_03-genotype.txt XYZ_987_03-genotype.txt XYZ_988_03-genotype.txt XYZ_989_03-genotype.txt XYZ_TS0_03-genotype.txt XYZ_TS1_03-genotype.txt XYZ_TS2_03-genotype.txt XYZ_TS3_03-genotype.txt XYZ_TS4_03-genotype.txt XYZ_TS5_03-genotype.txt XYZ_TS6_03-genotype.txt XYZ_TS7_03-genotype.txt XYZ_TS8_03-genotype.txt \
--unplaced XYZ_986_01-unplaced.txt XYZ_987_01-unplaced.txt XYZ_988_01-unplaced.txt XYZ_989_01-unplaced.txt XYZ_TS0_01-unplaced.txt XYZ_TS1_01-unplaced.txt XYZ_TS2_01-unplaced.txt XYZ_TS3_01-unplaced.txt XYZ_TS4_01-unplaced.txt XYZ_TS5_01-unplaced.txt XYZ_TS6_01-unplaced.txt XYZ_TS7_01-unplaced.txt XYZ_TS8_01-unplaced.txt XYZ_986_02-unplaced.txt XYZ_987_02-unplaced.txt XYZ_988_02-unplaced.txt XYZ_989_02-unplaced.txt XYZ_TS0_02-unplaced.txt XYZ_TS1_02-unplaced.txt XYZ_TS2_02-unplaced.txt XYZ_TS3_02-unplaced.txt XYZ_TS4_02-unplaced.txt XYZ_TS5_02-unplaced.txt XYZ_TS6_02-unplaced.txt XYZ_TS7_02-unplaced.txt XYZ_TS8_02-unplaced.txt XYZ_986_03-unplaced.txt XYZ_987_03-unplaced.txt XYZ_988_03-unplaced.txt XYZ_989_03-unplaced.txt XYZ_TS0_03-unplaced.txt XYZ_TS1_03-unplaced.txt XYZ_TS2_03-unplaced.txt XYZ_TS3_03-unplaced.txt XYZ_TS4_03-unplaced.txt XYZ_TS5_03-unplaced.txt XYZ_TS6_03-unplaced.txt XYZ_TS7_03-unplaced.txt XYZ_TS8_03-unplaced.txt \
--control med_std_devs_controls`

With that error, I tried splitting the columns so only three were in a new file i.e (Locus, Median, SD) that also seem to break the code.

Here is the head of the file:   
locus	mu	sd	n
chr1-100046147-100046148-T		0.5072649390480486	26
chr1-100046171-100046172-T		0.8034020228787198	26
chr1-100046172-100046173-T		0.2366591261993879	26
chr1-100046174-100046175-T		0.3954863125492504	26
chr1-100046198-100046199-T		0.1964320008491538	26
chr1-100046212-100046213-T		0.34358476016658573	26

Trouble line:
chr12-88467823-88467824-G	1.8892232751532336	0.952022934375811	26

Thank you for your time!

**Comment by jgunti-code** [comment]
Hi, I was wondering if you had a solution to my error! Thank you.

**Comment by hdashnow** [comment]
Unfortunately I haven't been able to replicate the issue, so I can't debug it. Is it possible to share a subset of your bam files that can reproduce the issue? I also need to know exactly which version you used. The code you mentioned is not in a current release, rather it's still in active development, so I'd need to know exactly which Git hash it was to know what you used.
